# Generated by Django 3.1.2 on 2020-11-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bull_and_bear', '0002_saved_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_predictions',
            name='date_predicted',
            field=models.CharField(max_length=10),
        ),
    ]
